CREATE TABLE follows
(
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    following_user_id INTEGER,
    followed_user_id  INTEGER,
    CONSTRAINT pk_follows PRIMARY KEY (id)
);

CREATE TABLE posts
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content       VARCHAR(255),
    creation_date TIMESTAMP WITHOUT TIME ZONE,
    user_id       INTEGER,
    CONSTRAINT pk_posts PRIMARY KEY (id)
);

CREATE TABLE users
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_name VARCHAR(255),
    e_mail    VARCHAR(255),
    password  VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE follows
    ADD CONSTRAINT FK_FOLLOWS_ON_FOLLOWED_USER FOREIGN KEY (followed_user_id) REFERENCES users (id);

ALTER TABLE follows
    ADD CONSTRAINT FK_FOLLOWS_ON_FOLLOWING_USER FOREIGN KEY (following_user_id) REFERENCES users (id);

ALTER TABLE posts
    ADD CONSTRAINT FK_POSTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);